"""实际锁定原生保存后异常：验证产品保留暂存原工程，而非测试代理副本。"""
import hashlib,json,os,subprocess,sys,tempfile,unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DOMAIN=json.loads((ROOT/'skill-suite.json').read_text())['pluginId']
SKILL=Path(os.environ['CRAFT_INSTALLED_SKILL_ROOT']).resolve() if os.environ.get('CRAFT_INSTALLED_SKILL_ROOT') else ROOT/'skills'/(DOMAIN+'-use')
INSTALLATION=os.environ.get('CRAFT_PRESERVED_STAGE_INSTALLATION')
@unittest.skipUnless(INSTALLATION,'requires explicitly verified native runtime installation')
class NativePreservedStageTests(unittest.TestCase):
 def test_post_save_protocol_fault_preserves_original_stage_and_blocks_replay(self):
  from PIL import Image
  installation=json.loads(Path(INSTALLATION).read_text());records=[]
  for fault in ['malformed','scalar','missing','ambiguous','nonfinite','tool-content']:
   with self.subTest(fault=fault),tempfile.TemporaryDirectory() as temporary:
    root=Path(temporary);output=root/'delivery';skill=SKILL;suffix={'filmcraft':'fcproj','effectcraft':'ecproj','photocraft':'pcraft','vectorcraft':'vectorcraft'}[DOMAIN]
    plans={'vectorcraft':{'document':{'name':'Recovery','width':32,'height':32,'units':'Pixels'},'operations':[{'command':'shape.rectangle','params':{'x':4,'y':4,'width':8,'height':8},'as':'shape'}],'exports':[{'format':'png','artboard':0}]},'effectcraft':{'document':{'name':'Recovery','width':32,'height':32,'frameRate':12,'duration':1},'operations':[{'command':'layer.newShape','params':{'kind':'rounded','name':'Badge','size':[8,8],'position':[16,16],'fill':'#ef5b36'},'as':'badge'}],'frames':[],'exports':[]},'photocraft':{'document':{'name':'Recovery','width':32,'height':32,'background':'#faf4e8'},'operations':[],'exports':[]},'filmcraft':{'document':{'name':'Recovery','width':32,'height':32,'frameRate':{'num':12,'den':1}},'operations':[],'frames':[],'exports':[]}}
    plan=plans[DOMAIN]
    if DOMAIN=='filmcraft':
     image=root/'still.png';Image.new('RGBA',(32,32),(239,91,54,255)).save(image);plan['assets']={'still':{'path':str(image),'sha256':hashlib.sha256(image.read_bytes()).hexdigest()}};plan['operations']=[{'command':'asset.import','params':{'asset':'still'},'as':'still'},{'command':'timeline.place','params':{'item':{'$ref':'still.item'},'track':'V1','time':'0','sourceIn':'0','duration':'254016000000','insert':False},'as':'clip'}]
    path=root/'plan.json';path.write_text(json.dumps(plan));log=root/'saves.jsonl';capture=root/('test-capture.'+suffix);reply=root/'reply.json';args=[sys.executable,'-I','-B',str(ROOT/'tests/fixtures/workflow_protocol_injection.py'),str(ROOT/'tests/fixtures/protocol_proxy.py'),fault,str(log),str(capture),str(reply),str(skill/'scripts/workflow.py'),str(path),'--output',str(output),'--runtime-home',installation['runtimeHome']]
    result=subprocess.run(args,capture_output=True,text=True,timeout=90);self.assertEqual(result.returncode,1,result.stdout+result.stderr);self.assertTrue(json.loads(result.stdout)['error'].startswith('outcome_unknown:'));saves=[json.loads(l) for l in log.read_text().splitlines()];self.assertEqual(len(saves),1);self.assertTrue(saves[0]['saveSucceeded'])
    self.assertTrue((output/'failure.json').is_file(),'product deleted failed stage without a recovery record')
    failure=json.loads((output/'failure.json').read_text());self.assertEqual(failure['outcome'],'outcome_unknown');self.assertFalse(failure['replayAllowed']);self.assertEqual(failure['lastAttempt']['phase'],'submitted');self.assertIn({'filmcraft':'file.saveAs','effectcraft':'save_project','photocraft':'doc_save','vectorcraft':'document.save'}[DOMAIN],json.dumps(failure['lastAttempt']));stage=(output/failure['stage']).resolve();self.assertTrue(stage.is_dir());self.assertTrue((stage/'failure.json').is_file());projects=list(stage.glob('*.'+suffix));self.assertTrue(projects,'original native project disappeared');project=projects[0];self.assertEqual(hashlib.sha256(project.read_bytes()).hexdigest(),saves[0]['sha256'])
    for name,entry in failure['files'].items():self.assertEqual(hashlib.sha256((stage/name).read_bytes()).hexdigest(),entry['sha256'])
    operations={'filmcraft':[{'command':'file.open','params':{'path':{'$ref':'project.path'}}},{'command':'sequence.inspect','params':{}}],'effectcraft':[{'tool':'open_project','params':{'path':{'$ref':'project.path'}}},{'tool':'get_comp','params':{}}],'photocraft':[{'tool':'doc_open','params':{'path':{'$ref':'project.path'}}},{'tool':'doc_inspect','params':{}}],'vectorcraft':[{'command':'document.open','params':{'path':{'$ref':'project.path'}}},{'command':'document.json','params':{}}]}[DOMAIN]
    inspect=root/'inspect.json';inspect.write_text(json.dumps({'schema':'craft-command-plan/v1','operations':operations}));reopen=subprocess.run([sys.executable,'-I','-B',str(skill/'scripts/commands.py'),'run',str(inspect),'--input','project='+str(project),'--output',str(root/'inspection'),'--runtime-home',installation['runtimeHome']],capture_output=True,text=True,timeout=90);self.assertEqual(reopen.returncode,0,reopen.stdout+reopen.stderr)
    retry=subprocess.run(args,capture_output=True,text=True,timeout=90);self.assertEqual(retry.returncode,1);self.assertIn('output_exists',retry.stdout);self.assertEqual(log.read_text().count('saveSucceeded'),1);self.assertEqual(hashlib.sha256(project.read_bytes()).hexdigest(),saves[0]['sha256']);self.assertFalse((output/'manifest.json').exists());records.append({'fault':fault,'result':'PASS','originalStagePreserved':True,'nativeReopened':True,'noReplay':True,'nativeSaveCount':1,'partialFiles':len(failure['files'])})
  if os.environ.get('CRAFT_PRESERVED_STAGE_EVIDENCE'):Path(os.environ['CRAFT_PRESERVED_STAGE_EVIDENCE']).write_text(json.dumps({'schema':'craft-native-failed-stage/v1','domain':DOMAIN,'result':'PASS','cases':records,'scope':'candidate source with locked installed native CLI; original retained stage inspected and reopened; proxy capture is not recovery input'},indent=2)+'\n')
